# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-03 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20180503_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='desc',
            field=models.TextField(verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(upload_to='static/upload/goodstype', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='title',
            field=models.CharField(max_length=30, verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='users',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='启用'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uname',
            field=models.CharField(max_length=30, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='users',
            name='uphone',
            field=models.CharField(max_length=20, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='users',
            name='upwd',
            field=models.CharField(max_length=30, verbose_name='密码'),
        ),
    ]
