# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-07 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20180507_0632'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmallBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='广告位')),
                ('picture', models.ImageField(upload_to='static/upload/smallbanner', verbose_name='图片')),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='picture',
            field=models.ImageField(upload_to='static/upload/banner', verbose_name='图片'),
        ),
    ]
