# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20180507_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('num', models.IntegerField()),
                ('pic', models.ImageField(upload_to='')),
                ('uphone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='index.Users')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(max_length=30, verbose_name='商品名称'),
        ),
    ]
