# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180509_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goods',
            new_name='title',
        ),
    ]
