# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20180509_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='uphone',
            field=models.CharField(max_length=30),
        ),
    ]
